_wandb:
    value:
        cli_version: 0.21.2
        e:
            kxory981wrdvygkcucc5x5x5prkg2uq0:
                codePath: train_yeast.py
                codePathLocal: train_yeast.py
                cpu_count: 112
                cpu_count_logical: 112
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "432834084864"
                        used: "1285242880"
                email: lausingsamuel@gmail.com
                executable: /home/samuel06/venv/bin/python
                git:
                    commit: 8d7f3f1524b38a6491d1942e39745eef74f1eccb
                    remote: https://github.com/StarrryNight/yorzoi-modified.git
                gpu: NVIDIA H100 80GB HBM3
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Hopper
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-6b1f7009-7ad2-dc6b-363e-b99f4fc8d5fa
                host: g1.nibi.sharcnet
                memory:
                    total: "2164170407936"
                os: Linux-5.14.0-570.44.1.el9_6.x86_64-x86_64-INTEL-R-_XEON-R-_PLATINUM_8570-with-glibc2.37
                program: /scratch/samuel06/yorzoi/train_yeast.py
                python: CPython 3.11.5
                root: /scratch/samuel06/yorzoi
                slurm:
                    cluster_name: nibi
                    conf: /etc/slurm/slurm.conf
                    cpus_on_node: "1"
                    gpus_on_node: "1"
                    gpus_per_node: "1"
                    gtids: "0"
                    home: /opt/software/slurm/current
                    job_account: def-cdeboer_gpu
                    job_cpus_per_node: "1"
                    job_end_time: "1768957247"
                    job_gid: "3155611"
                    job_gpus: "25"
                    job_id: "7207282"
                    job_name: interactive
                    job_nodelist: g1
                    job_num_nodes: "1"
                    job_partition: gpubase_interac
                    job_qos: normal
                    job_start_time: "1768955447"
                    job_uid: "3155611"
                    job_user: samuel06
                    jobid: "7207282"
                    launch_node_ipaddr: 10.39.0.11
                    localid: "0"
                    mem_per_node: "32768"
                    mpi_type: pmix
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: g1
                    oom_kill_step: "0"
                    pmix_mapping_serv: (vector,(0,1,1))
                    pmixp_abort_agent_port: "61652"
                    prio_process: "0"
                    procid: "0"
                    pty_port: "61651"
                    pty_win_col: "139"
                    pty_win_row: "15"
                    restart_count: "0"
                    script_context: prolog_task
                    srun_comm_host: 10.39.0.11
                    srun_comm_port: "61653"
                    step_id: "4294967290"
                    step_launcher_port: "61653"
                    step_nodelist: g1
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "4294967290"
                    submit_dir: /scratch/samuel06/yorzoi
                    submit_host: l1.nibi.sharcnet
                    task_pid: "2703105"
                    tasks_per_node: "1"
                    tmpdir: /local/scratch/samuel06.7207282.0
                    topology_addr: top.gswitch.g1
                    topology_addr_pattern: switch.switch.node
                startedAt: "2026-01-21T00:34:01.987763Z"
                writerId: kxory981wrdvygkcucc5x5x5prkg2uq0
        m: []
        python_version: 3.11.5
        t:
            "1":
                - 1
                - 11
                - 49
            "2":
                - 1
                - 11
                - 49
            "3":
                - 16
            "4": 3.11.5
            "5": 0.21.2
            "6": 4.57.6
            "12": 0.21.2
            "13": linux-x86_64
epochs:
    value: 80
lr:
    value: 6e-05
